---
# NodeMCU
#
# An ESP32-based board with 4MB flash, Wi-Fi and Bluetooth
# Chip description: WROOM32
#
# Chip is ESP32-D0WD-V3 (revision v3.1)
# Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse,
# Coding Scheme None
# Crystal is 40MHz
#
# https://www.amazon.nl/-/en/dp/B0CL9VZKMT
#

esp32:
  board: denky32
  framework:
    type: esp-idf
    # esp-idf is needed to have better performance on Bluetooth Proxy vs Arduino
    # Switch to esp-idf to resolve memory issues - ventilation project exceeds
    # flash space
    # Previous note: "Zehnder module fails on esp-idf" - testing if still true
    # type: arduino

light:
  - platform: status_led
    name: "Status LED"
    id: "${device_id}_status_led"
    # internal: true # Use this to hide the sensor from Home Assistant
    pin:
      number: GPIO2
      inverted: false
