---
# NodeMCU
#
# An ESP32-based board with 4MB flash, Wi-Fi and Bluetooth
# Chip description: WROOM32
# 
# Chip is ESP32-D0WD-V3 (revision v3.1)
# Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
# Crystal is 40MHz
#
# https://www.amazon.nl/-/en/dp/B0CL9VZKMT
#

esp32:
  board: denky32
  framework:
    type: arduino
    # esp-idf is needed to have a better performance on Bluetooth Proxy vs Arduino
    # Unfortunately, the Zehnder module fails on esp-idf
    # type: esp-idf

light:
  - platform: status_led
    name: "Status LED"
    id: "${device_id}_status_led"
    # internal: true # Use this to hide the sensor from Home Assistant
    pin:
      number: GPIO2
      inverted: false
