#
# Sensors
#

sensor:

  # TP-Link Smart Home - Power Outlets
  - platform: template
    sensors:
      # Plug 1 - Ready changed from 6 to 4 at 2020-02-01 as it triggered too many false positives
      washing_machine_status:
        friendly_name_template: "{{ states.switch.washing_machine_smart_plug.friendly_name }} Status"  
        value_template: >-  
          {% if states('sensor.washing_machine_smart_plug_current_consumption') == 'unavailable' %}  
            Unavailable
          {% elif (states('sensor.washing_machine_smart_plug_current_consumption')|float <= 1) %}  
            Off
          {% elif (states('sensor.washing_machine_smart_plug_current_consumption')|float <= 4) %}  
            On - Washing Machine Ready
          {% elif (states('sensor.washing_machine_smart_plug_current_consumption')|float|round == 6) %}  
            On - Dryer Ready
          {% elif (states('sensor.washing_machine_smart_plug_current_consumption')|float|round >= 650) %}  
            On - Drying
          {% else %} 
            On - Washing
          {% endif %}

  # External IP Address
  - platform: rest
    resource: https://api.ipify.org/?format=json
    name: External IP
    value_template: "{{ value_json.ip }}"

  # P2000
  - platform: p2000
    scan_interval: 20
    regios: 12
    radius: 4000
    contains: !secret zone_home_municipality

  # Shodan
  - platform: shodan
    api_key: !secret shodan_api_key
    query: !secret domain_fqdn

  # Greenchoice
  - platform: greenchoice
    name: greenchoice
    password: !secret greenchoicepass
    username: !secret greenchoiceuser

rest:
  # Top 2000 / NPO Radio 2 sensor by Stefan S. and Helmer
  # https://github.com/helmerzNL/HA-Configuration/blob/main/Packages/house/media/top2000_sensor.yaml
  - scan_interval: 60
    method: GET
    headers:
      User-Agent: Home Assistant
      Content-Type: application/json
    resource: https://www.nporadio2.nl/api/miniplayer/info?channel=npo-radio-2
    sensor:
      - name: NPO Radio 2 - Huidige song - basic
        json_attributes_path: "$.data.radioTrackPlays.data[0].radioTracks"
        json_attributes:
          - artist
          - name
          - coverUrl
        value_template: "{{ value_json['data']['radioTrackPlays']['data'][0]['radioTracks'].name }}"
      - name: NPO Radio 2 - Huidige song - extra
        json_attributes_path: "$.data.radioTrackPlays.data[0].cmsChartEditionPositions"
        json_attributes:
          - position
          - lastPosition
          - totalPositions
        value_template: "OK"
      - name: NPO Radio 2 - Vorige song - basic
        json_attributes_path: "$.data.radioTrackPlays.data[1].radioTracks"
        json_attributes:
          - artist
          - name
          - coverUrl
        value_template: "{{ value_json['data']['radioTrackPlays']['data'][1]['radioTracks'].name }}"
      - name: NPO Radio 2 - Vorige song - extra
        json_attributes_path: "$.data.radioTrackPlays.data[1].cmsChartEditionPositions"
        json_attributes:
          - position
          - lastPosition
          - totalPositions
        value_template: "OK"
      - name: NPO Radio 2 - Huidige Programma
        json_attributes_path: "$.data.radioBroadcasts.data[0]"
        json_attributes:
          - name
          - from
          - until
        value_template: "{{ value_json['data']['radioBroadcasts']['data'][0].name }}"
      - name: NPO Radio 2 - Huidige Programma Logo
        json_attributes_path: "$.data.radioBroadcasts.data[0].radioPhotoAssets"
        json_attributes:
          - url
        value_template: "OK"
      - name: NPO Radio 2 - Huidige Presentator
        json_attributes_path: "$.data.radioBroadcasts.data[0].radioPresenters[0]"
        json_attributes:
          - name
        value_template: "{{ value_json['data']['radioBroadcasts']['data'][0]['radioPresenters'][0].name }}"
      - name: NPO Radio 2 - Volgende Programma
        json_attributes_path: "$.data.upcomingBroadcasts.data[0]"
        json_attributes:
          - name
          - from
          - until
        value_template: "OK"
      - name: NPO Radio 2 - Volgende Programma Logo
        json_attributes_path: "$.data.upcomingBroadcasts.data[0].radioPhotoAssets"
        json_attributes:
          - url
        value_template: "OK"
      - name: NPO Radio 2 - Volgende Presentator
        json_attributes_path: "$.data.upcomingBroadcasts.data[0].radioPresenters[0]"
        json_attributes:
          - name
        value_template: "{{ value_json['data']['upcomingBroadcasts']['data'][0]['radioPresenters'][0].name }}"
