blueprint:
  name: Clear iOS Notification
  description: "# \U0001F4E2 Clear iOS Notification \n**Version: 1.02**\n\nUse this
    template to create a script to retract a notification which has been sent to your
    iOS device \U0001F4AC\U0001F509\n\n \U0001F642\n<details> <summary><b>The Script
    Process:</b> - Click here to expand</summary>\n\n\n  - **Location-Based States:**
    Home or Not Home\n\n    - Opt to remove notification from one or multiple devices.
    Compatible with Apple iOS only.\n\nRequired = *\n"
  domain: script
  author: HelmerNL
  input:
    device_notify_settings:
      name: Clear Mobile App Notification*
      icon: mdi:devices
      collapsed: false
      input:
        notify_device:
          name: Devices Targeted
          description: 'Select the devices from which the notification will be removed.

            '
          default: []
          selector:
            device:
              filter:
              - integration: mobile_app
              multiple: true
        notify_tag:
          name: Tag to be cleared*
          description: 'Enter the message tag you want to be removed from the device.
            Please note that you need to enter the exact same tag you used to send
            the notification. All other notifications (which have a different tag
            or group) will stay on the device.

            '
          default: "Enter Tag Here \U0001F642"
          selector:
            text:
              multiple: false
              multiline: false
  source_url: https://gist.github.com/helmerzNL/06904c85f6e24b30420cbdc4b2b3adff
mode: parallel
max_exceeded: silent
variables:
  notify_device: !input notify_device
  notify_tag: !input notify_tag
  device_message_data: "{% set message = namespace(data={}) %} {% set push = namespace(data={})
    %}{% if notify_tag != [] %}\n  {% set message.data = dict(message.data, **{ 'tag':
    notify_tag }) %}\n{% endif %} {{ message.data }}"
  filtered_devices: '{{ notify_device}}'
sequence:
- choose:
  - alias: Check if notification is enabled
    conditions:
    - '{{ filtered_devices | length > 0 }}'
    sequence:
    - alias: Send a notification to each device
      repeat:
        for_each: '{{ filtered_devices }}'
        sequence:
        - action: notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify
            }}
          data:
            title: clear
            message: clear_notification
            data: '{{ device_message_data }}'
