---
#
# The safe_mode button platform allows you to restart your node into safe mode
#  remotely through Home Assistant.
#
# https://esphome.io/components/button/safe_mode.html
#

platform: safe_mode
id: button_restart_safe_mode
name: "Restart (Safe Mode)"
