---
#
# Set Baud Rate for UART from Home Assistant
#

id: "${device_id}_change_baud_rate"
name: Baud rate
platform: template
options:
  - "2400"
  - "9600"
  - "38400"
  - "57600"
  - "115200"
  - "256000"
  - "512000"
  - "921600"
initial_option: "9600"
optimistic: true
restore_value: True
internal: false
entity_category: config
icon: mdi:swap-horizontal
set_action:
  - lambda: |-
      id(${device_id}_uart).flush();
      uint32_t new_baud_rate = stoi(x);
      ESP_LOGD("change_baud_rate", "Changing baud rate from %i to %i",id(${device_id}_uart).get_baud_rate(), new_baud_rate);
      if (id(${device_id}_uart).get_baud_rate() != new_baud_rate) {
        id(${device_id}_uart).set_baud_rate(new_baud_rate);
        id(${device_id}_uart).load_settings();
      }
