---
# WiFi Info Text Sensor
#
# The wifi_info text sensor platform exposes different WiFi information via
# text sensors.
#
#

platform: wifi_info
ip_address:
  name: "IP Address"
  icon: mdi:ip-network
ssid:
  name: "SSID"
  icon: mdi:wifi-settings
bssid:
  name: "BSSID"
  icon: mdi:identifier
mac_address:
  name: "MAC"
  icon: mdi:identifier
