---
# ESPHome Core configuration
#
# Sets the defaults for the main core configuration of my ESPHome devices.
#
# https://esphome.io/components/esphome.html
#

esphome:
  name: ${hostname}
  friendly_name: ${device_name}
  comment: ${project_description}
  area: ${device_area}
  project:
    name: ${project_name}
    version: ${device_name}
  on_boot:
    priority: -100
    then:
      - logger.log: "Debug mode disabled"
      - logger.set_level:
          level: INFO

preferences:
  # Prevent rapid changes to a component from being quickly written to the flash and wearing it out
  # https://esphome.io/components/esphome.html#adjusting-flash-writes
  flash_write_interval: 1d
