---
# Version Text Sensor
#
# The version text sensor platform exposes the ESPHome version the firmware was
# compiled against as a text sensor.
#
# https://esphome.io/components/text_sensor/version.html
#

text_sensor:
  - <<: !include ../text_sensors/version.yaml
