esphome:
  name: living-room
  comment: Various sensors such as CO2
  friendly_name: Living Room
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: !secret living_room_ip_address

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret living_room_ap_ssid
    password: !secret living_room_ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret living_room_api_encryption_key

ota:
  password: !secret living_room_ota_password
  platform: esphome

# BRUH Multisensor
sensor:
  - platform: dht
    pin: D7
    temperature:
      name: "Multisensor Temperature"
    humidity:
      name: "Multisensor Humidity"
  - platform: adc
    pin: A0
    name: "Multisensor Brightness"
    unit_of_measurement: lux
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;
  # CO2 Sensor
  - platform: mhz19
    id: mhz19_living_room
    co2:
      name: "MH-Z19 CO2 Value"
    temperature:
      name: "MH-Z19 Temperature"
    update_interval: 60s
    automatic_baseline_calibration: false

binary_sensor:
  - platform: gpio
    pin: D5
    name: "Multisensor Motion"
    device_class: motion

output:
  - platform: esp8266_pwm
    pin: D1
    id: redgpio
  - platform: esp8266_pwm
    pin: D2
    id: greengpio
  - platform: esp8266_pwm
    pin: D3
    id: bluegpio

light:
  - platform: rgb
    name: "Multisensor Light"
    red: redgpio
    green: greengpio
    blue: bluegpio

# CO2 Sensor
uart:
  rx_pin: D9
  tx_pin: D10
  baud_rate: 9600

switch:
  - platform: template
    name: "MH-Z19 Automatic Base Calibration"
    optimistic: true
    on_turn_on:
      mhz19.abc_enable: mhz19_living_room
    on_turn_off:
      mhz19.abc_disable: mhz19_living_room
