#
# Zehnder Remote Control device
# Usage: controls my Zehnder ComfoFan S ventilation system

substitutions:
  hostname: zehnder-comfofan
  device_name: Zehnder ComfoFan
  device_id: zehnder_comfofan
  device_area: Fuse Box
  project_name: ESPHome.Zehnder
  project_description: Ventilation Control System

# Note: I import my common configurations all at once to prevent duplicated configs across my ESPHome devices
packages:
  <<: !include_dir_named common
  board: !include boards/esp8266.yaml
  zehnder-comfofan: !include components/zehnder-comfofan.yaml

logger:
  id: component_logger
  level: INFO
  # Make sure to select 'CP2102 USB to UART Bridge Controller'
  baud_rate: 115200
