---
name: Config Sync

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    uses: DevSecNinja/.github/.github/workflows/config-sync.yml@24acc67adf1be33089e73b2fdbdb4be8c12d145b # v3.2.0
    permissions:
      contents: write
      pull-requests: write
